### PR TITLE
fix: Don't upload code source if "include_source" is false

### LINKED ISSUE #227: Setting include_sources:false should not upload SourceBundles
### Environment

Fastlane plugin version: 1.16.0
Xcode 14.3

### Steps to Reproduce

1. Follow steps in the [sentry docs for uploading debug symbols](https://docs.sentry.io/platforms/apple/dsym/#fastlane)

2. Using the fastlane plugin with this snippet:

```ruby
sentry_upload_dif(
  auth_token: my_auth_token,
  org_slug: my_org_slug,
  project_slug: my_project_slug,
  include_sources: false,
)
```

3. Added `no_sources: true,` when I noticed symbols were being uploaded but the same result.

### Expected Result

I expected that no SourceBundles would be uploaded.

We have rules at my company about not uploading our source code to places that we don't control. I think SourceBundles are equivalent to source code being uploaded so I really don't want these uploaded.

> The resulting source bundle is an archive containing all source files referenced by a specific debug information file.

[Source](https://docs.sentry.io/product/cli/dif/#creating-source-bundles)

### Actual Result

When I go to the project in sentry then to Settings -> Debug Files I see this:

Screenshot 2023-12-20 at 10 53 03

### Further questions

- Am I using this tool wrong?
- Are SourceBundles not actual source code and we should feel safe to have them uploaded?
- Is there a way to upload dSYM files and exclude source code snippets?

### PR DESCRIPTION
**Pull request by brustolin**
We're just checking whether `include_source` is nil or not in order to pass the argument to sentry-cli.

Fixing this and checking whether `include_source` is true

close #227

### CODE REVIEW

File: spec/sentry_upload_dif_spec.rb [hunk 1]
```diff
@@ -284,6 +284,18 @@
         end").runner.execute(:test)
       end
 
+      it "dont includes --include_sources when false" do
```
Comment (brustolin) [inline spec/sentry_upload_dif_spec.rb:287]:
```suggestion
      it "dont include --include_sources when false" do
```

**Review by philipphofmann — APPROVED** [review]
LGTM
